#!/bin/bash

set -e
set -u
set -f

function forcelink
{
    SRC=$1
    DST=$2
    sudo ln -s -f $SRC $DST
}

wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

sudo cp /vagrant/sources.list /etc/apt/sources.list
echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list

sudo apt-get update -qq
sudo apt-get install -y libclang1-3.8 python3-pip git-core

sudo ln -s -f /usr/lib/llvm-3.8/lib/libclang-3.8.so.1 /usr/lib/llvm-3.8/lib/libclang-3.8.so
sudo ln -s -f /usr/lib/llvm-3.8/lib/libclang.so.1 /usr/lib/llvm-3.8/lib/libclang.so
sudo pip3 install libclang_py3

