#!/bin/bash

set -e
set -u
set -f

function forcelink
{
    SRC=$1
    DST=$2
    sudo ln -s -f $SRC $DST
}

wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

sudo cp /vagrant/sources.list /etc/apt/sources.list
echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee -a /etc/apt/sources.list
echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main" | sudo tee -a /etc/apt/sources.list

sudo apt-get update -qq
sudo apt-get install -y libclang1-3.6 libclang1-3.7 python3-pip
sudo pip3 install libclang_py3

